"""
cq_template.py
--------------
Builds the HTML string for a GitLab Code Quality report PDF.
"""

from __future__ import annotations

import io
from datetime import datetime

from .cq_parser import CqReport, SEVERITY_ORDER

# ── Severity palette ──────────────────────────────────────────────────────────

SEVERITY_COLOR: dict[str, str] = {
    "blocker":  "#c0392b",
    "critical": "#e74c3c",
    "major":    "#e67e22",
    "minor":    "#f39c12",
    "info":     "#2980b9",
}

# ── Localization ──────────────────────────────────────────────────────────────

_LABELS: dict[str, dict[str, str]] = {
    "en": {
        "default_title":  "Code Quality Report",
        "confidential":   "CONFIDENTIAL – AUTHORIZED PERSONNEL ONLY",
        "report_date":    "Report Date",
        "source_file":    "Source File",
        "total_issues":   "Total Issues",
        "page_footer":    "Code Quality Report",
        "sec1":           "1. Executive Summary",
        "sec2":           "2. Top Issue Types (Top 15)",
        "sec2_phpstan":   "2. Top PHPStan Messages (Top 15)",
        "sec_rules":      "PHPStan Rules / Identifiers",
        "sec3":           "3. Most Affected Files (Top 20)",
        "sec4":           "4. Issue Details (Sorted by Severity — All)",
        "sec5":           "5. General Recommendations",
        "rec_priority":   "Blocker and Critical issues should be addressed first; aim to eliminate at least one severity level per sprint cycle.",
        "rec_tabs":       "Tab indentation ({count} occurrences): Configure your editor and CI to enforce spaces consistently across the codebase.",
        "rec_spacing":    "Operator and control structure spacing ({count} occurrences): Use an automated code formatter (e.g. PHP-CS-Fixer, Prettier) to enforce consistent style.",
        "rec_line_len":   "Line length violations ({count} occurrences): Set a maximum line length in your linter config and break long lines for readability.",
        "rec_formatter":  "Integrate an automated code formatter into your CI pipeline to prevent style issues from being introduced in new code.",
        "rec_phpcs":      "Run PHP_CodeSniffer (phpcs) with the PSR-12 standard as a required CI check on every merge request.",
        "rec_phpstan":    "Treat PHPStan findings as static analysis defects, not style warnings; review each message and fix root causes or document intentional exceptions in the PHPStan baseline.",
        "rec_phpstan_level":"Increase PHPStan strictness gradually after the current findings are resolved; keep the level pinned in CI so new regressions fail merge requests.",
        "rec_legacy":     "Legacy/vendor-like files with concentrated findings should be isolated, upgraded, or excluded with explicit justification instead of repeatedly suppressing individual findings.",
        "col_check":      "Check",
        "col_message":    "Message",
        "col_identifier": "Identifier",
        "analyzer":       "Analyzer",
        "analyzer_version":"Analyzer Version",
        "rules":          "Rules / Identifiers",
        "col_count":      "Count",
        "col_ratio":      "Ratio",
        "col_dist":       "Distribution",
        "col_file":       "File Path",
        "col_findings":   "Issues",
        "col_severity":   "Severity",
        "col_file_line":  "File : Line",
        "col_description":"Description",
        "summary": (
            "This report was automatically generated from the Code Quality output file "
            "<em>{source_file}</em>. The analysis identified <strong>{total}</strong> "
            "code quality issues in total. Issues are summarized by severity level below."
        ),
        "footer_note": "This report was automatically generated by <em>gl2pdf</em>. All findings may require manual verification.",
    },
    "tr": {
        "default_title":  "Kod Kalitesi Raporu",
        "confidential":   "GİZLİ – YETKİLİ KİŞİLERE ÖZEL",
        "report_date":    "Rapor Tarihi",
        "source_file":    "Kaynak Dosya",
        "total_issues":   "Toplam Sorun",
        "page_footer":    "Kod Kalitesi Raporu",
        "sec1":           "1. Yönetici Özeti",
        "sec2":           "2. En Çok Görülen Sorun Türleri (İlk 15)",
        "sec2_phpstan":   "2. En Çok Görülen PHPStan Mesajları (İlk 15)",
        "sec_rules":      "PHPStan Kuralları / Identifier'ları",
        "sec3":           "3. En Çok Etkilenen Dosyalar (İlk 20)",
        "sec4":           "4. Sorun Detayları (Kritiklik Sırasına Göre — Tümü)",
        "sec5":           "5. Genel Tavsiyeler",
        "rec_priority":   "Blocker ve Critical sorunlar öncelikli olarak ele alınmalı; her sprint döngüsünde en az bir kritiklik seviyesi sıfırlanmayı hedeflemelidir.",
        "rec_tabs":       "Tab girintileme ({count} adet): Editör ve CI yapılandırması boşluk kullanımını zorunlu kılacak şekilde ayarlanmalıdır.",
        "rec_spacing":    "Operatör ve kontrol yapısı boşlukları ({count} adet): PHP-CS-Fixer gibi otomatik bir kod biçimlendirici kullanılarak tutarlı stil sağlanmalıdır.",
        "rec_line_len":   "Satır uzunluğu ihlalleri ({count} adet): Linter yapılandırmasında maksimum satır uzunluğu belirlenmeli, uzun satırlar okunabilirlik için bölünmelidir.",
        "rec_formatter":  "Yeni kodda stil sorunlarının oluşmasını önlemek için CI pipeline'a otomatik kod biçimlendirici entegre edilmelidir.",
        "rec_phpcs":      "Her merge request'te PSR-12 standardıyla PHP_CodeSniffer (phpcs) zorunlu CI kontrolü olarak çalıştırılmalıdır.",
        "rec_phpstan":    "PHPStan bulguları stil uyarısı değil statik analiz hatası olarak ele alınmalı; her mesaj incelenerek kök neden düzeltilmeli veya bilinçli istisnalar PHPStan baseline içinde belgelenmelidir.",
        "rec_phpstan_level":"Mevcut bulgular kapatıldıktan sonra PHPStan katılık seviyesi kademeli artırılmalı; yeni regresyonların merge request aşamasında engellenmesi için seviye CI üzerinde sabitlenmelidir.",
        "rec_legacy":     "Bulguların yoğunlaştığı legacy/vendor-benzeri dosyalar tek tek bastırılmak yerine izole edilmeli, güncellenmeli veya açık gerekçeyle kapsam dışı bırakılmalıdır.",
        "col_check":      "Kural",
        "col_message":    "Mesaj",
        "col_identifier": "Identifier",
        "analyzer":       "Analiz Aracı",
        "analyzer_version":"Analiz Aracı Sürümü",
        "rules":          "Kurallar / Identifier'lar",
        "col_count":      "Adet",
        "col_ratio":      "Oran",
        "col_dist":       "Dağılım",
        "col_file":       "Dosya Yolu",
        "col_findings":   "Sorun Sayısı",
        "col_severity":   "Kritiklik",
        "col_file_line":  "Dosya : Satır",
        "col_description":"Açıklama",
        "summary": (
            "Bu rapor, <em>{source_file}</em> adlı Kod Kalitesi çıktısından otomatik olarak üretilmiştir. "
            "Analizde toplamda <strong>{total}</strong> kod kalitesi sorununa ulaşılmıştır. "
            "Sorunlar kritiklik düzeylerine göre aşağıda özetlenmektedir."
        ),
        "footer_note": "Bu rapor <em>gl2pdf</em> aracı ile otomatik olarak oluşturulmuştur. Tüm bulgular manuel doğrulama gerektirebilir.",
    },
}


def _L(lang: str, key: str) -> str:
    return _LABELS.get(lang, _LABELS["en"]).get(key, _LABELS["en"][key])


# ── Public entry point ────────────────────────────────────────────────────────

def build_html(
    report: CqReport,
    title: str | None = None,
    repo: str | None = None,
    lang: str = "en",
) -> str:
    """Return a complete HTML document string for the given Code Quality report."""
    if lang not in _LABELS:
        lang = "en"

    L = lambda key: _L(lang, key)  # noqa: E731

    now = datetime.now().strftime("%d %B %Y %H:%M")
    cover_title = _esc(title) if title else L("default_title")
    repo_html = f'<div class="cover-repo">{_esc(repo)}</div>' if repo else ""
    source_file = _esc(str(report.source_file.name))

    return _HTML_TEMPLATE.format(
        lang             = lang,
        report_date      = now,
        source_file      = source_file,
        total            = report.total,
        cover_title      = cover_title,
        repo_html        = repo_html,
        lbl_confidential = L("confidential"),
        lbl_report_date  = L("report_date"),
        lbl_source_file  = L("source_file"),
        lbl_total        = L("total_issues"),
        lbl_page_footer  = L("page_footer"),
        lbl_sec1         = L("sec1"),
        lbl_sec2         = L("sec2"),
        lbl_sec3         = L("sec3"),
        lbl_sec4         = L("sec4"),
        lbl_col_check    = L("col_check"),
        lbl_col_count    = L("col_count"),
        lbl_col_ratio    = L("col_ratio"),
        lbl_col_dist     = L("col_dist"),
        lbl_col_file     = L("col_file"),
        lbl_col_findings = L("col_findings"),
        lbl_col_severity = L("col_severity"),
        lbl_col_file_line= L("col_file_line"),
        lbl_col_desc     = L("col_description"),
        lbl_footer_note  = L("footer_note"),
        summary_text     = L("summary").format(source_file=source_file, total=report.total),
        severity_cards   = _severity_cards(report),
        severity_legend  = _severity_legend(report),
        top_checks_rows  = _top_checks_rows(report),
        top_files_rows   = _top_files_rows(report),
        detail_rows      = _detail_rows(report),
    )


# ── Fragment builders ─────────────────────────────────────────────────────────

def _severity_cards(report: CqReport) -> str:
    parts = []
    for sev in SEVERITY_ORDER:
        count = report.severity_counts.get(sev, 0)
        if count == 0:
            continue
        color = SEVERITY_COLOR.get(sev, "#95a5a6")
        parts.append(
            f'<div class="card" style="border-top:4px solid {color};">'
            f'<div class="card-count" style="color:{color};">{count}</div>'
            f'<div class="card-label">{sev.upper()}</div>'
            f'</div>'
        )
    return "\n".join(parts)


def _severity_legend(report: CqReport) -> str:
    items = []
    for sev in SEVERITY_ORDER:
        cnt = report.severity_counts.get(sev, 0)
        if cnt == 0:
            continue
        color = SEVERITY_COLOR.get(sev, "#95a5a6")
        items.append(
            f'<span class="legend-item">'
            f'<span class="legend-dot" style="background:{color};"></span>'
            f'{sev.upper()}: <strong>{cnt}</strong>'
            f'</span>'
        )
    return " &nbsp; ".join(items)


def _top_checks_rows(report: CqReport) -> str:
    rows = []
    for i, (check, cnt) in enumerate(report.top_checks, 1):
        pct = cnt / report.total * 100 if report.total else 0
        rows.append(
            f"<tr>"
            f"<td>{i}</td>"
            f'<td class="mono small">{_esc(check)}</td>'
            f'<td class="num">{cnt}</td>'
            f'<td class="num">{pct:.1f}%</td>'
            f'<td><div class="bar" style="width:{min(pct * 3, 100):.0f}px;background:#FA002A;"></div></td>'
            f"</tr>"
        )
    return "\n".join(rows)


def _top_files_rows(report: CqReport) -> str:
    rows = []
    for i, (fname, cnt) in enumerate(report.top_files, 1):
        rows.append(
            f"<tr>"
            f"<td>{i}</td>"
            f'<td class="mono">{_esc(fname)}</td>'
            f'<td class="num">{cnt}</td>'
            f"</tr>"
        )
    return "\n".join(rows)


_DETAIL_BATCH = 500
_DETAIL_LIMIT = 2000  # cap to keep PDF render time reasonable


def _detail_rows(report: CqReport) -> str:
    buf = io.StringIO()
    batch: list[str] = []

    for i, issue in enumerate(report.sorted_issues(), 1):
        if i > _DETAIL_LIMIT:
            buf.write(
                f'<tr><td colspan="5" style="text-align:center;color:#888;font-style:italic;padding:10px;">'
                f'… {report.total - _DETAIL_LIMIT:,} more issues not shown (showing top {_DETAIL_LIMIT:,} by severity)'
                f'</td></tr>'
            )
            break
        color = SEVERITY_COLOR.get(issue.severity, "#95a5a6")
        batch.append(
            f"<tr>"
            f"<td>{i}</td>"
            f'<td><span class="badge" style="background:{color};">{_esc(issue.severity.upper())}</span></td>'
            f'<td class="mono small">{_esc(issue.path)}:{issue.line}</td>'
            f'<td class="mono small">{_esc(issue.check_name)}</td>'
            f"<td>{_esc(issue.description)}</td>"
            f"</tr>"
        )
        if len(batch) >= _DETAIL_BATCH:
            buf.write("\n".join(batch))
            buf.write("\n")
            batch.clear()

    if batch:
        buf.write("\n".join(batch))

    return buf.getvalue()


# ── HTML escape helper ────────────────────────────────────────────────────────

def _esc(text: str) -> str:
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


# ── Master HTML/CSS template ──────────────────────────────────────────────────

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="{lang}">
<head>
<meta charset="UTF-8">
<title>{cover_title}</title>
<style>
  @page {{
    size: A4;
    margin: 15mm 12mm 15mm 12mm;
    @bottom-center {{
      content: "{lbl_page_footer}  |  " counter(page) " / " counter(pages);
      font-size: 8pt;
      color: #888;
    }}
  }}

  * {{ box-sizing: border-box; margin: 0; padding: 0; }}

  body {{
    font-family: "DejaVu Sans", "Helvetica Neue", Arial, sans-serif;
    font-size: 9pt;
    color: #222;
    background: #fff;
  }}

  .cover {{
    height: 267mm;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    background: #ffffff;
    border-bottom: 6px solid #FA002A;
    color: #1a1a1a;
    text-align: center;
    padding: 40px;
  }}
  .cover h1 {{ font-size: 26pt; font-weight: 700; letter-spacing: .5px; margin-bottom: 10px; color: #1a1a1a; }}
  .cover-repo {{ font-size: 13pt; font-weight: 400; color: #555; margin-bottom: 32px; }}
  .cover .meta {{ font-size: 9.5pt; color: #666; line-height: 2; }}
  .cover .tag {{
    display: inline-block; background: #FA002A; color: #fff;
    border-radius: 4px; padding: 5px 18px; margin-top: 24px;
    font-size: 9.5pt; letter-spacing: .5px; font-weight: 600;
  }}

  .section {{ margin-top: 24px; }}
  .section-title {{
    font-size: 13pt; font-weight: 700; color: #FA002A;
    border-bottom: 2px solid #FA002A; padding-bottom: 4px; margin-bottom: 12px;
  }}

  .cards {{ display: flex; flex-wrap: wrap; gap: 12px; margin-bottom: 14px; }}
  .card {{ flex: 1 1 90px; background: #f8f9fa; border-radius: 6px; padding: 12px 10px; text-align: center; min-width: 80px; }}
  .card-count {{ font-size: 22pt; font-weight: 700; }}
  .card-label {{ font-size: 7.5pt; color: #555; margin-top: 4px; text-transform: uppercase; letter-spacing: .5px; }}

  .legend {{ margin-bottom: 12px; line-height: 2.2; font-size: 8.5pt; }}
  .legend-item {{ margin-right: 4px; }}
  .legend-dot {{ display: inline-block; width: 10px; height: 10px; border-radius: 50%; margin-right: 3px; vertical-align: middle; }}

  .info-box {{
    background: #fff0f2; border-left: 4px solid #FA002A; border-radius: 4px;
    padding: 10px 14px; margin-bottom: 14px; font-size: 8.5pt; line-height: 1.8;
  }}
  .info-box strong {{ color: #FA002A; }}

  table {{ width: 100%; border-collapse: collapse; font-size: 8pt; }}
  th {{ background: #FA002A; color: #fff; padding: 5px 7px; text-align: left; font-weight: 600; font-size: 7.5pt; }}
  td {{ padding: 4px 7px; border-bottom: 1px solid #e8e8e8; vertical-align: top; }}
  tr:nth-child(even) td {{ background: #fff5f6; }}
  .num {{ text-align: right; }}
  .mono {{ font-family: "DejaVu Sans Mono", "Courier New", monospace; font-size: 7pt; word-break: break-all; }}
  .small {{ font-size: 7.5pt; }}
  .bar {{ height: 8px; border-radius: 3px; min-width: 2px; }}
  .badge {{ display: inline-block; color: #fff; border-radius: 3px; padding: 1px 6px; font-size: 7pt; font-weight: 700; white-space: nowrap; }}
  .page-break {{ page-break-after: always; }}
  p.summary {{ line-height: 1.7; margin-bottom: 12px; font-size: 9pt; }}
</style>
</head>
<body>

<div class="cover">
  <h1>{cover_title}</h1>
  {repo_html}
  <div class="meta">
    <div>{lbl_source_file}: {source_file}</div>
    <div>{lbl_report_date}: {report_date}</div>
  </div>
  <div class="tag">{lbl_confidential}</div>
</div>
<div class="page-break"></div>

<div class="section">
  <div class="section-title">{lbl_sec1}</div>
  <div class="info-box">
    <strong>{lbl_source_file}:</strong> {source_file} &nbsp;|&nbsp;
    <strong>{lbl_total}:</strong> {total} &nbsp;|&nbsp;
    <strong>{lbl_report_date}:</strong> {report_date}
  </div>
  <p class="summary">{summary_text}</p>
  <div class="cards">
{severity_cards}
  </div>
  <div class="legend">{severity_legend}</div>
</div>

<div class="section" style="margin-top:20px;">
  <div class="section-title">{lbl_sec2}</div>
  <table>
    <thead>
      <tr><th>#</th><th>{lbl_col_check}</th><th class="num">{lbl_col_count}</th><th class="num">{lbl_col_ratio}</th><th>{lbl_col_dist}</th></tr>
    </thead>
    <tbody>
{top_checks_rows}
    </tbody>
  </table>
</div>
<div class="page-break"></div>

<div class="section">
  <div class="section-title">{lbl_sec3}</div>
  <table>
    <thead>
      <tr><th>#</th><th>{lbl_col_file}</th><th class="num">{lbl_col_findings}</th></tr>
    </thead>
    <tbody>
{top_files_rows}
    </tbody>
  </table>
</div>
<div class="page-break"></div>

<div class="section">
  <div class="section-title">{lbl_sec4}</div>
  <table>
    <thead>
      <tr><th>#</th><th>{lbl_col_severity}</th><th>{lbl_col_file_line}</th><th>{lbl_col_check}</th><th>{lbl_col_desc}</th></tr>
    </thead>
    <tbody>
{detail_rows}
    </tbody>
  </table>
</div>

<p style="margin-top:30px;font-size:7pt;color:#aaa;text-align:center;">
  {lbl_footer_note} &nbsp;|&nbsp; {report_date}
</p>

</body>
</html>
"""
