"""
template.py
-----------
Builds the HTML string that will be converted to PDF.
All styling lives here so the rest of the code stays clean.
"""

from __future__ import annotations

import io
from datetime import datetime

from .parser import SastReport

# ── Severity palette ──────────────────────────────────────────────────────────

SEVERITY_ORDER = ["Critical", "High", "Medium", "Low", "Info", "Unknown"]

SEVERITY_COLOR: dict[str, str] = {
    "Critical": "#FA002A",
    "High":     "#D86A00",
    "Medium":   "#E89005",
    "Low":      "#1F8B4C",
    "Info":     "#2066A1",
    "Unknown":  "#849293",
}

# ── Localization ──────────────────────────────────────────────────────────────

_LABELS: dict[str, dict[str, str]] = {
    "en": {
        "default_title":    "SAST Security Report",
        "kicker":           "gl2pdf SAST Report",
        "confidential":     "CONFIDENTIAL – AUTHORIZED PERSONNEL ONLY",
        "analyzer":         "Analyzer",
        "scanner":          "Scanner",
        "report_date":      "Report Date",
        "source_file":      "Source File",
        "scan_type":        "Scan Type",
        "scan_type_val":    "SAST (Static Application Security Testing)",
        "tool":             "Tool",
        "total_findings":   "Total Findings",
        "page_footer":      "SAST Security Report",
        "sec1":             "1. Executive Summary",
        "sec2":             "2. Top Vulnerability Types (Top 15)",
        "sec3":             "3. Most Affected Files (Top 20)",
        "sec4":             "4. Finding Details (Sorted by Severity — All)",
        "sec5":             "5. General Recommendations",
        "col_vuln":         "Vulnerability",
        "col_count":        "Count",
        "col_ratio":        "Ratio",
        "col_dist":         "Distribution",
        "col_file":         "File Path",
        "col_findings":     "Findings",
        "col_severity":     "Severity",
        "col_file_line":    "File : Line",
        "col_cwe":          "CWE",
        "col_owasp":        "OWASP",
        "summary": (
            "This report was automatically generated from the SAST output file "
            "<em>{source_file}</em>. The analysis was performed using the "
            "<em>{scanner_name}</em> engine and identified <strong>{total}</strong> "
            "security findings in total. Findings are summarized by severity level below."
        ),
        "footer_note":      "This report was automatically generated by <em>gl2pdf</em>. All findings may require manual verification.",
        "rec_priority":     "<li><strong>Critical and High findings</strong> should be addressed first; aim to eliminate at least one severity level per sprint cycle.</li>",
        "rec_rfi":          "<li>PHP <strong>Remote File Inclusion</strong> ({count} occurrences): Restrict path parameters from user input using a whitelist; disable <code>allow_url_include</code>.</li>",
        "rec_eval":         "<li><strong>Eval Injection</strong> ({count} occurrences): Avoid <code>eval()</code> and dynamic code execution; apply strict input validation when unavoidable.</li>",
        "rec_hash":         "<li><strong>Weak Hash Algorithms</strong>: Replace MD5/SHA-1 with SHA-256 (integrity) or bcrypt/Argon2 (passwords).</li>",
        "rec_regex":        "<li><strong>Dynamic Regex</strong>: Define regex patterns as static constants; never compile them from user input (ReDoS risk).</li>",
        "rec_cmd":          "<li><strong>OS Command Injection</strong> ({count} occurrences): Never pass user input directly to system commands; parameterize <code>subprocess</code>/<code>exec</code> calls.</li>",
        "rec_cicd":         "<li>Integrate SAST scanning into the CI/CD pipeline to run on every <em>merge request</em>; new critical findings should break the build.</li>",
    },
    "tr": {
        "default_title":    "SAST Güvenlik Raporu",
        "kicker":           "gl2pdf SAST Raporu",
        "confidential":     "GİZLİ – YETKİLİ KİŞİLERE ÖZEL",
        "analyzer":         "Analiz Motoru",
        "scanner":          "Tarayıcı",
        "report_date":      "Rapor Tarihi",
        "source_file":      "Kaynak Dosya",
        "scan_type":        "Tarama Türü",
        "scan_type_val":    "SAST (Statik Uygulama Güvenlik Testi)",
        "tool":             "Araç",
        "total_findings":   "Toplam Bulgu",
        "page_footer":      "SAST Güvenlik Raporu",
        "sec1":             "1. Yönetici Özeti",
        "sec2":             "2. En Çok Görülen Güvenlik Açığı Türleri (İlk 15)",
        "sec3":             "3. En Çok Etkilenen Dosyalar (İlk 20)",
        "sec4":             "4. Bulgu Detayları (Kritiklik Sırasına Göre — Tümü)",
        "sec5":             "5. Genel Tavsiyeler",
        "col_vuln":         "Açıklık Adı",
        "col_count":        "Adet",
        "col_ratio":        "Oran",
        "col_dist":         "Dağılım",
        "col_file":         "Dosya Yolu",
        "col_findings":     "Bulgu Sayısı",
        "col_severity":     "Kritiklik",
        "col_file_line":    "Dosya : Satır",
        "col_cwe":          "CWE",
        "col_owasp":        "OWASP",
        "summary": (
            "Bu rapor, <em>{source_file}</em> adlı SAST çıktısından otomatik olarak üretilmiştir. "
            "Analiz; <em>{scanner_name}</em> motoru kullanılarak yürütülmüş olup toplamda "
            "<strong>{total}</strong> güvenlik bulgusuna ulaşılmıştır. "
            "Bulgular kritiklik düzeylerine göre aşağıda özetlenmektedir."
        ),
        "footer_note":      "Bu rapor <em>gl2pdf</em> aracı ile otomatik olarak oluşturulmuştur. Tüm bulgular manuel doğrulama gerektirebilir.",
        "rec_priority":     "<li><strong>Kritik ve Yüksek bulgular öncelikli</strong> olarak ele alınmalı; her sprint döngüsünde en az bir kritiklik seviyesi sıfırlanmayı hedeflemelidir.</li>",
        "rec_rfi":          "<li>PHP <strong>Remote File Inclusion</strong> ({count} adet): Kullanıcıdan gelen yol parametreleri whitelist ile kısıtlanmalı, <code>allow_url_include</code> kapatılmalıdır.</li>",
        "rec_eval":         "<li><strong>Eval Injection</strong> ({count} adet): <code>eval()</code> / dinamik kod çalıştırma kullanımından kaçınılmalı; zorunlu durumlarda katı giriş denetimi uygulanmalıdır.</li>",
        "rec_hash":         "<li><strong>Zayıf Hash Algoritmaları</strong>: MD5 / SHA-1 yerine SHA-256 (veri bütünlüğü) veya bcrypt/Argon2 (parola) kullanılmalıdır.</li>",
        "rec_regex":        "<li><strong>Dinamik Regex</strong>: Düzenli ifade kalıpları statik sabitlerle tanımlanmalı, kullanıcı girdisinden derlenmemelidir (ReDoS riski).</li>",
        "rec_cmd":          "<li><strong>OS Command Injection</strong> ({count} adet): Sistem komutlarına doğrudan kullanıcı girdisi geçirilmemeli; <code>subprocess</code> / <code>exec</code> çağrıları parametrize edilmelidir.</li>",
        "rec_cicd":         "<li>CI/CD pipeline'a SAST taraması entegre edilerek her <em>merge request</em>'te otomatik çalıştırılmalı; yeni kritik bulgu oluşturması build'i kırmalıdır.</li>",
    },
}

SUPPORTED_LANGUAGES = list(_LABELS.keys())


def _L(lang: str, key: str) -> str:
    return _LABELS.get(lang, _LABELS["en"]).get(key, _LABELS["en"][key])


# ── Public entry point ────────────────────────────────────────────────────────

def build_html(
    report: SastReport,
    title: str | None = None,
    repo: str | None = None,
    lang: str = "en",
) -> str:
    """Return a complete HTML document string for the given report.

    All vulnerabilities are included — no limit.
    Rows are written in batches via StringIO to avoid O(n²) string
    concatenation on large reports.

    Args:
        title: Cover page title. Defaults to the localized 'SAST Security Report'.
        repo:  Repository / project name shown below the title on the cover.
        lang:  Report language. Supported: 'en' (default), 'tr'.
    """
    if lang not in _LABELS:
        lang = "en"

    L = lambda key: _L(lang, key)  # noqa: E731

    now = datetime.now().strftime("%d %B %Y %H:%M")
    cover_title = _esc(title) if title else L("default_title")
    repo_html = f'<div class="cover-repo">{_esc(repo)}</div>' if repo else ""
    source_file = _esc(str(report.source_file.name))

    return _HTML_TEMPLATE.format(
        lang             = lang,
        report_date      = now,
        analyzer_name    = _esc(report.scan.analyzer_name),
        analyzer_version = _esc(report.scan.analyzer_version),
        scanner_name     = _esc(report.scan.scanner_name),
        scanner_version  = _esc(report.scan.scanner_version),
        source_file      = source_file,
        total            = report.total,
        cover_title      = cover_title,
        repo_html        = repo_html,
        # labels
        lbl_confidential = L("confidential"),
        lbl_analyzer     = L("analyzer"),
        lbl_scanner      = L("scanner"),
        lbl_report_date  = L("report_date"),
        lbl_source_file  = L("source_file"),
        lbl_scan_type    = L("scan_type"),
        lbl_scan_type_val= L("scan_type_val"),
        lbl_tool         = L("tool"),
        lbl_total        = L("total_findings"),
        lbl_page_footer  = L("page_footer"),
        lbl_sec1         = L("sec1"),
        lbl_sec2         = L("sec2"),
        lbl_sec3         = L("sec3"),
        lbl_sec4         = L("sec4"),
        lbl_sec5         = L("sec5"),
        lbl_col_vuln     = L("col_vuln"),
        lbl_col_count    = L("col_count"),
        lbl_col_ratio    = L("col_ratio"),
        lbl_col_dist     = L("col_dist"),
        lbl_col_file     = L("col_file"),
        lbl_col_findings = L("col_findings"),
        lbl_col_severity = L("col_severity"),
        lbl_col_file_line= L("col_file_line"),
        lbl_col_cwe      = L("col_cwe"),
        lbl_col_owasp    = L("col_owasp"),
        lbl_footer_note  = L("footer_note"),
        summary_text     = L("summary").format(
            source_file=source_file,
            scanner_name=_esc(report.scan.scanner_name),
            total=report.total,
        ),
        # data
        severity_cards   = _severity_cards(report),
        severity_legend  = _severity_legend(report),
        top_types_rows   = _top_types_rows(report),
        top_files_rows   = _top_files_rows(report),
        detail_rows      = _detail_rows(report),
        recommendations  = _recommendations(report, lang),
    )


# ── Fragment builders ─────────────────────────────────────────────────────────

def _severity_cards(report: SastReport) -> str:
    parts = []
    for sev in SEVERITY_ORDER:
        count = report.severity_counts.get(sev, 0)
        if count == 0:
            continue
        color = SEVERITY_COLOR.get(sev, "#95a5a6")
        parts.append(
            f'<div class="card" style="border-top:4px solid {color};">'
            f'<div class="card-count" style="color:{color};">{count}</div>'
            f'<div class="card-label">{sev}</div>'
            f'</div>'
        )
    return "\n".join(parts)


def _severity_legend(report: SastReport) -> str:
    items = []
    for sev in SEVERITY_ORDER:
        cnt = report.severity_counts.get(sev, 0)
        if cnt == 0:
            continue
        color = SEVERITY_COLOR.get(sev, "#95a5a6")
        items.append(
            f'<span class="legend-item">'
            f'<span class="legend-dot" style="background:{color};"></span>'
            f'{sev}: <strong>{cnt}</strong>'
            f'</span>'
        )
    return " &nbsp; ".join(items)


def _top_types_rows(report: SastReport) -> str:
    rows = []
    for i, (name, cnt) in enumerate(report.top_names, 1):
        pct = cnt / report.total * 100 if report.total else 0
        rows.append(
            f"<tr>"
            f"<td>{i}</td>"
            f"<td>{_esc(name)}</td>"
            f'<td class="num">{cnt}</td>'
            f'<td class="num">{pct:.1f}%</td>'
            f'<td><div class="bar" style="width:{min(pct * 3, 100):.0f}px;background:#FA002A;"></div></td>'
            f"</tr>"
        )
    return "\n".join(rows)


def _top_files_rows(report: SastReport) -> str:
    rows = []
    for i, (fname, cnt) in enumerate(report.top_files, 1):
        rows.append(
            f"<tr>"
            f"<td>{i}</td>"
            f'<td class="mono">{_esc(fname)}</td>'
            f'<td class="num">{cnt}</td>'
            f"</tr>"
        )
    return "\n".join(rows)


_DETAIL_BATCH = 500


def _detail_rows(report: SastReport) -> str:
    buf = io.StringIO()
    batch: list[str] = []

    for i, v in enumerate(report.sorted_vulnerabilities(), 1):
        color     = SEVERITY_COLOR.get(v.severity, "#95a5a6")
        cwe_str   = ", ".join(v.cwe[:2])   or "—"
        owasp_str = ", ".join(v.owasp[:1]) or "—"
        batch.append(
            f"<tr>"
            f"<td>{i}</td>"
            f'<td><span class="badge" style="background:{color};">{_esc(v.severity)}</span></td>'
            f'<td class="mono small">{_esc(v.file)}:{v.start_line}</td>'
            f"<td>{_esc(v.name)}</td>"
            f'<td class="small">{_esc(cwe_str)}</td>'
            f'<td class="small">{_esc(owasp_str)}</td>'
            f"</tr>"
        )
        if len(batch) >= _DETAIL_BATCH:
            buf.write("\n".join(batch))
            buf.write("\n")
            batch.clear()

    if batch:
        buf.write("\n".join(batch))

    return buf.getvalue()


def _recommendations(report: SastReport, lang: str = "en") -> str:
    L = lambda key: _L(lang, key)  # noqa: E731
    name_counts = dict(report.top_names)
    items: list[str] = []

    items.append(L("rec_priority"))

    rfi_key = next(
        (k for k in name_counts if "Remote File Inclusion" in k or "include/require" in k.lower()),
        None,
    )
    if rfi_key:
        items.append(L("rec_rfi").format(count=name_counts[rfi_key]))

    eval_key = next(
        (k for k in name_counts if "Eval" in k or "eval" in k.lower()), None
    )
    if eval_key:
        items.append(L("rec_eval").format(count=name_counts[eval_key]))

    hash_key = next(
        (k for k in name_counts if "weak hash" in k.lower() or "hash" in k.lower()), None
    )
    if hash_key:
        items.append(L("rec_hash"))

    regex_key = next(
        (k for k in name_counts if "regular expression" in k.lower()), None
    )
    if regex_key:
        items.append(L("rec_regex"))

    cmd_key = next(
        (k for k in name_counts if "OS Command" in k or "command injection" in k.lower()), None
    )
    if cmd_key:
        items.append(L("rec_cmd").format(count=name_counts[cmd_key]))

    items.append(L("rec_cicd"))

    return "\n".join(f"    {item}" for item in items)


# ── HTML escape helper ────────────────────────────────────────────────────────

def _esc(text: str) -> str:
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


# ── Master HTML/CSS template ──────────────────────────────────────────────────

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="{lang}">
<head>
<meta charset="UTF-8">
<title>{cover_title}</title>
<style>
  @page {{
    size: A4;
    margin: 15mm 12mm 15mm 12mm;
    @bottom-center {{
      content: "{lbl_page_footer}  |  " counter(page) " / " counter(pages);
      font-size: 8pt;
      color: #888;
    }}
  }}

  * {{ box-sizing: border-box; margin: 0; padding: 0; }}

  body {{
    font-family: "DejaVu Sans", "Helvetica Neue", Arial, sans-serif;
    font-size: 9pt;
    color: #222;
    background: #fff;
  }}

  /* ── Cover ── */
  .cover {{
    height: 267mm;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    background: #ffffff;
    border-bottom: 6px solid #FA002A;
    color: #1a1a1a;
    text-align: center;
    padding: 40px;
  }}
  .cover h1 {{
    font-size: 26pt;
    font-weight: 700;
    letter-spacing: .5px;
    margin-bottom: 10px;
    color: #1a1a1a;
  }}
  .cover-repo {{
    font-size: 13pt;
    font-weight: 400;
    color: #555;
    margin-bottom: 32px;
  }}
  .cover .meta {{
    font-size: 9.5pt;
    color: #666;
    line-height: 2;
  }}
  .cover .tag {{
    display: inline-block;
    background: #FA002A;
    color: #fff;
    border-radius: 4px;
    padding: 5px 18px;
    margin-top: 24px;
    font-size: 9.5pt;
    letter-spacing: .5px;
    font-weight: 600;
  }}

  /* ── Sections ── */
  .section {{ margin-top: 24px; }}
  .section-title {{
    font-size: 13pt;
    font-weight: 700;
    color: #FA002A;
    border-bottom: 2px solid #FA002A;
    padding-bottom: 4px;
    margin-bottom: 12px;
  }}

  /* ── Cards ── */
  .cards {{ display: flex; flex-wrap: wrap; gap: 12px; margin-bottom: 14px; }}
  .card {{
    flex: 1 1 90px;
    background: #fff;
    border-radius: 6px;
    padding: 14px 10px;
    text-align: center;
    min-width: 80px;
    box-shadow: 0 2px 5px rgba(0,0,0,0.05);
  }}
  .card-count {{ font-size: 22pt; font-weight: 700; }}
  .card-label {{
    font-size: 7.5pt;
    color: #555;
    margin-top: 2px;
    text-transform: uppercase;
    letter-spacing: .5px;
  }}

  /* ── Legend ── */
  .legend {{ margin-bottom: 12px; line-height: 2.2; font-size: 8.5pt; }}
  .legend-item {{ margin-right: 4px; }}
  .legend-dot {{
    display: inline-block;
    width: 10px; height: 10px;
    border-radius: 50%;
    margin-right: 3px;
    vertical-align: middle;
  }}

  /* ── Info box ── */
  .info-box {{
    background: #fff0f2;
    border-left: 4px solid #FA002A;
    border-radius: 4px;
    padding: 10px 14px;
    margin-bottom: 14px;
    font-size: 8.5pt;
    line-height: 1.8;
  }}
  .info-box strong {{ color: #FA002A; }}

  /* ── Tables ── */
  table {{ width: 100%; border-collapse: collapse; font-size: 8pt; }}
  th {{
    background: #FA002A;
    color: #fff;
    padding: 5px 7px;
    text-align: left;
    font-weight: 600;
    font-size: 7.5pt;
  }}
  td {{ padding: 4px 7px; border-bottom: 1px solid #e8e8e8; vertical-align: top; }}
  tr:nth-child(even) td {{ background: #fff5f6; }}
  .num {{ text-align: right; }}
  .mono {{ font-family: "DejaVu Sans Mono", "Courier New", monospace; font-size: 7pt; word-break: break-all; }}
  .small {{ font-size: 7.5pt; }}

  /* ── Bar ── */
  .bar {{ height: 8px; border-radius: 3px; min-width: 2px; }}

  /* ── Badge ── */
  .badge {{
    display: inline-block;
    color: #fff;
    border-radius: 4px;
    padding: 2px 8px;
    font-size: 7.5pt;
    font-weight: 700;
    white-space: nowrap;
    text-transform: uppercase;
    letter-spacing: 0.3px;
  }}

  /* ── Misc ── */
  .note {{ font-size: 7.5pt; color: #777; margin-bottom: 6px; font-style: italic; }}
  .page-break {{ page-break-after: always; }}
  p.summary {{ line-height: 1.7; margin-bottom: 12px; font-size: 9pt; }}
  ol.recommendations {{ padding-left: 18px; line-height: 2; font-size: 8.5pt; }}
  ol.recommendations code {{
    background: #eef; border-radius: 3px; padding: 1px 4px;
    font-family: "DejaVu Sans Mono", monospace; font-size: 7.5pt;
  }}
</style>
</head>
<body>

<!-- COVER -->
<div class="cover">
  <h1>{cover_title}</h1>
  {repo_html}
  <div class="meta">
    <div>{lbl_analyzer}: {analyzer_name} v{analyzer_version}</div>
    <div>{lbl_scanner}: {scanner_name} v{scanner_version}</div>
    <div>{lbl_report_date}: {report_date}</div>
  </div>
  <div class="tag">{lbl_confidential}</div>
</div>
<div class="page-break"></div>

<!-- SECTION 1 -->
<div class="section">
  <div class="section-title">{lbl_sec1}</div>
  <div class="info-box">
    <strong>{lbl_source_file}:</strong> {source_file} &nbsp;|&nbsp;
    <strong>{lbl_scan_type}:</strong> {lbl_scan_type_val} &nbsp;|&nbsp;
    <strong>{lbl_tool}:</strong> {analyzer_name} {analyzer_version} / {scanner_name} {scanner_version}<br>
    <strong>{lbl_total}:</strong> {total} &nbsp;|&nbsp;
    <strong>{lbl_report_date}:</strong> {report_date}
  </div>
  <p class="summary">{summary_text}</p>
  <div class="cards">
{severity_cards}
  </div>
  <div class="legend">{severity_legend}</div>
</div>

<!-- SECTION 2 -->
<div class="section" style="margin-top:20px;">
  <div class="section-title">{lbl_sec2}</div>
  <table>
    <thead>
      <tr>
        <th>#</th><th>{lbl_col_vuln}</th>
        <th class="num">{lbl_col_count}</th><th class="num">{lbl_col_ratio}</th><th>{lbl_col_dist}</th>
      </tr>
    </thead>
    <tbody>
{top_types_rows}
    </tbody>
  </table>
</div>
<div class="page-break"></div>

<!-- SECTION 3 -->
<div class="section">
  <div class="section-title">{lbl_sec3}</div>
  <table>
    <thead>
      <tr><th>#</th><th>{lbl_col_file}</th><th class="num">{lbl_col_findings}</th></tr>
    </thead>
    <tbody>
{top_files_rows}
    </tbody>
  </table>
</div>
<div class="page-break"></div>

<!-- SECTION 4 -->
<div class="section">
  <div class="section-title">{lbl_sec4}</div>
  <table>
    <thead>
      <tr>
        <th>#</th><th>{lbl_col_severity}</th><th>{lbl_col_file_line}</th>
        <th>{lbl_col_vuln}</th><th>{lbl_col_cwe}</th><th>{lbl_col_owasp}</th>
      </tr>
    </thead>
    <tbody>
{detail_rows}
    </tbody>
  </table>
</div>

<!-- SECTION 5 -->
<div class="section" style="margin-top:24px; page-break-before:always;">
  <div class="section-title">{lbl_sec5}</div>
  <ol class="recommendations">
{recommendations}
  </ol>
</div>

<p style="margin-top:30px;font-size:7pt;color:#aaa;text-align:center;">
  {lbl_footer_note} &nbsp;|&nbsp; {report_date}
</p>

</body>
</html>
"""
